staging-settings:
  user-workflow:
    workflow-name: "k17ce7ppz28n0wx5wq9vk95srn8255tf-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"
production-settings:
  user-workflow:
    workflow-name: "k17ce7ppz28n0wx5wq9vk95srn8255tf-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: "../secrets.yaml"
