staging-settings:
  user-workflow:
    workflow-name: "k1779vqkbgr88sm1n924323zk981pvap-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"
production-settings:
  user-workflow:
    workflow-name: "k1779vqkbgr88sm1n924323zk981pvap-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: "../secrets.yaml"
