staging-settings:
  user-workflow:
    workflow-name: "k17dnx68tjya99nmh71cehbe9181z1gj-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"
production-settings:
  user-workflow:
    workflow-name: "k17dnx68tjya99nmh71cehbe9181z1gj-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: "../secrets.yaml"
